export const SKILL_MD_CONTENT = `# MigrateProof

Generated by \`migrateproof install-skill\` — do not hand-edit,
regenerating this file will overwrite any changes.

Instructions for an AI coding agent: find the API changes this
repository's test suite would silently fail to catch, then close those
gaps.

## Default to acting, not asking

Do every step below yourself. Only stop and ask a single, specific
question when guessing would produce a wrong result that looks right —
never ask just to confirm something you can verify by reading the code.

## Workflow

1. Run \`npx migrateproof\`. It runs this project's existing test
   suite, mutates the API responses those tests receive, re-runs the
   affected tests, and reports every field whose change nothing caught.
   No setup, no config, no files to create.
2. For each reported gap, add the assertion that would catch it, to the
   test file the report names. A gap means the test ran happily against
   corrupted data — the fix is a real assertion about that field's
   value or type, not a broader smoke test.
3. Run \`npx migrateproof\` again. The gap you just fixed must now
   report as caught. If it does not, your assertion is not actually
   checking the mutated field.
4. Report what you closed and anything you could not, with the reason.

## Interpreting the report

- **gap** — the suite ran and noticed nothing. This is the actionable
  case, and it is worse than no coverage, because it looks covered.
- **no tests at all** — nothing to strengthen; the endpoint needs a test
  written from scratch. Say so rather than inventing assertions about
  business rules you cannot verify from the code.
- **could not be analyzed** — usually means the project mocks above the
  HTTP layer. Report it; do not work around it.

## What this does not do

It cannot tell you whether a business rule is correct — only whether
your tests would notice if the data changed. If nothing in this
repository states what "correct" means for a field, do not invent it.

For proving a specific, hand-stated business invariant against recorded
v1/v2 responses, see the fixture workflow in the README's advanced
section.
`;
